In [5]:
import torch

In [ ]:
# Create a 2D tensor with shape (5, 2)
# Values: 0, 1, 2, ..., 9 arranged in 5 rows and 2 columns
t = torch.arange(0, 10).reshape(5, 2)
print(t)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [ ]:
# Print the stride of the tensor
# Stride (2, 1) means:
#   - Move 2 elements in memory to go to the next row
#   - Move 1 element in memory to go to the next column
print(t.stride())

(2, 1)


### Understanding `tensor.stride()`
- A stride tells PyTorch how many elements (in memory) it must skip to move to the next item along a dimension.
- For the 2D tensor above (shape `5 x 2`), the first stride value corresponds to moving one row down, and the second value corresponds to moving one column across.
- Strides depend on how the tensor is laid out in memory; reshaping or transposing changes them even if the data visually looks similar.
- Contiguous tensors typically have decreasing strides (row-major order), but operations like `transpose` can swap stride values without copying data.

In [ ]:
# Compare strides across different tensor operations

# 1. Original tensor: standard row-major layout
print("Original tensor:")
print(t)
print("Shape:", t.shape)  # (5, 2)
print("Strides:", t.stride())  # (2, 1) - move 2 for next row, 1 for next column

# 2. Transpose: swaps dimensions and strides without copying data
print("\nAfter transpose (swap rows/cols):")
t_T = t.t()  # Transpose operation
print(t_T)
print("Shape:", t_T.shape)  # (2, 5) - dimensions swapped
print("Strides:", t_T.stride())  # (1, 2) - strides swapped too!

# 3. Flatten to 1D: contiguous view with single stride
print("\nView as 1D without copying:")
t_flat = t.view(-1)  # Reshape to 1D
print(t_flat)
print("Shape:", t_flat.shape)  # (10,)
print("Strides:", t_flat.stride())  # (1,) - move 1 element for next item


# 4. Slicing with step: creates non-contiguous view
print("\nNon-contiguous slice (every other row):")
t_slice = t[::2]  # Take every 2nd row
print(t_slice)
print("Shape:", t_slice.shape)  # (3, 2) - 3 rows, 2 columns
print("Strides:", t_slice.stride())  # (4, 1) - skip 4 elements for next row!

Original tensor:
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
Shape: torch.Size([5, 2])
Strides: (2, 1)

After transpose (swap rows/cols):
tensor([[0, 2, 4, 6, 8],
        [1, 3, 5, 7, 9]])
Shape: torch.Size([2, 5])
Strides: (1, 2)

View as 1D without copying:
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Shape: torch.Size([10])
Strides: (1,)

Non-contiguous slice (every other row):
tensor([[0, 1],
        [4, 5],
        [8, 9]])
Shape: torch.Size([3, 2])
Strides: (4, 1)
